name: webview_skops
description: Skor perilaku Siswa

publish_to: "none"

version: 1.4.0+14

environment:
  sdk: ^3.8.0

dependencies:
  carousel_slider: ^5.1.1
  change_app_package_name: ^1.0.0
  connectivity_plus: ^7.0.0
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  device_info_plus: ^11.4.0  
  double_back_to_close: ^2.0.0
  entry: ^1.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_custom_clippers: ^2.0.0
  flutter_svg: ^2.2.3
  freezed_annotation: ^3.0.0
  google_fonts: ^6.3.2
  http: ^1.5.0
  image_picker: ^1.2.1
  intl: ^0.20.2
  page_transition: ^2.2.1
  persistent_bottom_nav_bar: ^6.2.1
  shared_preferences: ^2.5.3
  sizer: ^3.1.3
  uuid: ^4.5.2
  webview_flutter: ^4.13.0

dev_dependencies:
  build_runner: ^2.4.8
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

flutter_gen:
  output: lib/core/assets/
  integrations:
    flutter_svg: true
  # assets:
  #   - assets/images/
  #   - assets/icons/
